<?php

namespace Database\Factories;

use App\Models\Patient;
use App\Models\InsuranceCompany;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

class PatientFactory extends Factory
{
    protected $model = Patient::class;

    public function definition(): array
    {
        $type = $this->faker->randomElement(['cash', 'insurance']);

        return [
            'file_number' => null, // Auto-generated by service
            'first_name' => $this->faker->firstName(),
            'middle_name' => $this->faker->firstName(),
            'last_name' => $this->faker->lastName(),
            'phone' => $this->faker->unique()->phoneNumber(),
            'email' => $this->faker->unique()->safeEmail(),
            'date_of_birth' => $this->faker->dateTimeBetween('-80 years', '-18 years'),
            'gender' => $this->faker->randomElement(['male', 'female']),
            'address' => $this->faker->address(),
            'city' => $this->faker->city(),
            'type' => $type,
            'insurance_company_id' => $type === 'insurance'
                ? InsuranceCompany::inRandomOrder()->first()?->id
                : null,
            'insurance_card_number' => $type === 'insurance'
                ? $this->faker->numerify('###-###-###')
                : null,
            'insurance_policyholder' => $type === 'insurance'
                ? $this->faker->name()
                : null,
            'insurance_expiry_date' => $type === 'insurance'
                ? $this->faker->dateTimeBetween('now', '+5 years')
                : null,
            'notes' => $this->faker->sentence(),
            'is_active' => true,
            'created_by' => User::admin()->first()?->id ?? 1,
        ];
    }

    /**
     * Configure factory for cash patient
     */
    public function cash(): static
    {
        return $this->state(function (array $attributes) {
            return [
                'type' => 'cash',
                'insurance_company_id' => null,
                'insurance_card_number' => null,
                'insurance_policyholder' => null,
                'insurance_expiry_date' => null,
            ];
        });
    }

    /**
     * Configure factory for insurance patient
     */
    public function insurance(): static
    {
        return $this->state(function (array $attributes) {
            return [
                'type' => 'insurance',
                'insurance_company_id' => InsuranceCompany::inRandomOrder()->first()?->id ?? 1,
                'insurance_card_number' => $this->faker->numerify('###-###-###'),
                'insurance_policyholder' => $this->faker->name(),
                'insurance_expiry_date' => $this->faker->dateTimeBetween('now', '+5 years'),
            ];
        });
    }
}
